name: Generate Data and Update Repository

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use your desired Python version (e.g., '3.8', '3.9')

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Execute Python Script
      run: python src/main.py

    - name: Commit and Push Changes
      run: |
        git config user.name "Xingjian508"
        git config user.email "xingjiw4@uci.edu"
        git add .
        git commit -m "Update data JSON"
        git push

