name: Generate Data

on:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: python3 pysrc/main.py

    - name: Commit and push if changes were made
      run: |
        git diff --exit-code || (git config user.name "Xingjian508" && git config user.email "xingjiw4@uci.edu" && git add -A && git commit -m "Update data" && git push)
      if: success()
it push
