name: Update Data

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install requests
        run: pip install requests

      - name: Run Python script
        run: python3 pysrc/main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Xingjian508"
          git config --global user.email "xingjiw4@uci.edu"
          git add .
          git commit -m "Update Data"
          git push origin main
        
        env:
          GITHUB_PAT: ${{ secrets.FOREX_WEBSITE }}

